### ISSUE TITLE
Add a commit hook to generate a list of calendar propers

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#234]
Related: #76, #210, #201, #121, #262

---

I propose to auto-generate calendar propers from the calendars in the romcal codebase using a commit hook.

I suggest to create a commit hook using the script below.

Note that the script below is a WIP. It definitely can be improved in many ways. Some of these improvements depend on other things (like localisation of celebration cycle names, titles, calendar names). Below I list potential improvements of the script, which might be dealt/implemented in separate issues/PRs. Also note that the TODO list is quite verbose. :smiley:

The current (initial) version of this script:

- works with English and Slovak locales only (Latin would work if `dayjs` would include Latin locale, which I hope is on the way with merging PR iamkun/dayjs#966). The reason behind this is that currently only those locales are supported which contain all strings localised;
- does not process `celebrations.ts`;
- presumes that either the calendar configuration is defined _entirely_ in the particular calendar **or** it is not defined in the particular calendar _at all_ and then the calendar configuration from `general.ts` is used; this might cause an issue, but should not, because when we use calendar configuration, we should _always_ define every option (key) in it.

---

TODO:
- [ ] also localise terms like `liturgical colour`, `rank`, `date`, `celebration`, `title` (both in singular and plural, probably even both nominative and genitive), as well as the values from `localeConfig` constant from the script;
- [ ] add another mandatory key to celebration definition and to the output JSON) which would contain human-readable string that would define the celebration date (note that we might want to localise the verbose ones):
   - fixed dates: `{year}-01-01` (Note: This one might be omited altogether, because this can be simply parsed from the current date definition. However, it might be easier to implement in this script if even for fixed dates this would be filled in);
   - fixed dates that are relative to other celebrations: `Monday after Pentecost Sunday`;
   - fixed dates that are moved to different dates when they ocur with celebrations of higher rank: `{year}-03-25; moved to Monday after First Sunday of Easter when ocurs either with Palm Sunday or is in the Holy Week`;
- [ ] add a column with changes (in celebration definition) in comparison with the GRC (aka `GRC change type`):
   - IMHO the easiest way to accomplish this is to add another mandatory key (e.g. `changeType`) to all celebration definitions with the following possible values (the values might be changed as required, however the key value must be an array, as there might be more than one change):
      - `date moved`;
      - `rank lowered`;
      - `additional title(s)`;
      - `removed title(s)`;
      - `celebration dropped`;
   - it might be even better if we could localise these values (as all and any other user-facing value/string);
- [ ] currently, the script relies on the order the celebrations are defined in calendar; we might want to sort them (order by date, but there would be two groups: celebrations with [semi-]fixed dates and celebrations which date depends on other celebration);
- [ ] add calendar metadata object (in calendar files) that would contain the following information (also available in the output JSON):
   - calendar name constant (e.g. `GENERAL_ROMAN_CALENDAR`);
   - localised calendar name (e.g. `General Roman Calendar` in English);
   - validation information:
      - `validated` [Boolean]:
         - if the calendar was validated;
      - `validationSourceType` ['official' | 'unofficial']:
         - if the calendar was validated (`validated`), what type of source was used to validate it;
      - `validationSourceName` [String]:
         - if the calendar was validated (`validated`), what is the name of the source (e.g. `Missale Romanamu, ed. typ. tertia`, `Roman Missal, ed. typ. tertia`, `decree`, `AAS`, `Notitiae`, `diocese` [even if the source is from the liturgical commission of that diocese], `other`);
      - `validationSourceUrl` [String]:
         - if the calendar was validated (`validated`) and if the source is available online, provide the URL address here;
- [ ] list holydays of obligation per proper (blocked by #76)
- [ ] process `celebration.ts` file when generating GRC Proper; or even better: move those celebrations into `general.ts` (see #210);
- [ ] add patronage titles when there are implemented (either into `Ranks` column or in a separate column; see #201);
- [ ] liturgical colours are currently obtained from the celebration definition (and therefore not all colours are output in the table), however, when #121 is implemented, we need to find a different way to gather the colours;
- [ ] we might want to improve format the MD table (I did not do anything major with it yet, as right now I wanted to demostrate what I mean by _creating calendar propers_);
- [ ] I would suggest to rename the `source` key used in celebration definitions to something else, as IMHO a `source` should be the source from where we got the celebration metadata.
- [ ] use fallback locales as in romcal:
   - currently, the script does not use any fallback language, that is: when a string is not localised, it would output `undefined`;
- [ ] we might want to get the configuration from `general.ts` data (stored in memory/variable), not directly from file;
- [ ] maybe someone can find a better way to create a JSON from calendar files (see lines 173-179 in the script file; it starts with `removeLinesBefore` variable definition);
- [ ] @emagnier: Is the default celebration cycle `temporale`? If yes, we could output it by default (i.e. when `cycles` object is empty).

---

Example output of the script using code from PR #213 is uploaded to [romcal Wiki](https://github.com/romcal/romcal/wiki/List-of-calendar-propers), as it contains 502,651, while GitHub permits maximum 65,536 characters in a comment.

---

<details>
   <summary><code>create_propers_from_cals.js</code></summary>

```js
/*
 * Generate all calendar propers using romcal data
 *
 * author:  Tukusej’s Sirs
 * date:    4 October 2020
 * version: 0.1
 *
 * Install dependencies: `npm install fs tablemark dayjs`
 */


// Modules
const fs = require('fs')
const tablemark = require('tablemark')
const dayjs = require('dayjs')
const utc = require('dayjs/plugin/utc')
dayjs.extend(utc)

// Constants
const repoRoot = '/home/ts/git/c10n/romcal_ts'  // TODO: Change this as required
const outFile = './test.md'  // TODO: Change this as required
const calPath = repoRoot + '/src/calendars'
const l10nPath = repoRoot + '/src/locales'
// TODO: Currently only those locales are supported which are localised for 100 %
// Note: It works as expected with Slovak locale (as it contains all strings from `en.ts`)
// Note: It doesn't work with Latin locale, because currently we miss the Latin locale in `dayjs` (currently, I wait when my PR will be merged); otherwise this work work just like English or Slovak locale
const locale = 'en'
// This is used to get the fixed date from the date definition more easily
const year = new Date().getFullYear()

// Set the locale for `dayjs`
// Note: This is used to get the fixed date from the date definition more easily
require('dayjs/locale/' + locale)
dayjs.locale(locale)

// Define the definite article
// TODO: Add this (somehow) to l10n files in romcal codebase
const localeConfig = {
   // Note: All keys should be defined in all locales (use empty string for `definiteArticle` if it is not available in a particular locale)
   en: {
      // TODO: Use lowercase `the` (or any other article) in l10n files and uppercase the first letter (or all letters) when needed
      definiteArticle: 'The',
      // Format that `dayjs` understands
      dayMonthFormat: 'D MMMM',
      celebrationName: 'Celebration name',
      rank: 'Rank',
      date: 'Date',
      liturgicalColors: 'Liturgical color(s)',
      titles: 'Title(s)',
      celebrationCycle: 'Celebration cycle',
      lookupSource: 'Lookup source',
      isPrioritized: 'Is prioritized?',
      grcChangeType: 'GRC change type'
   },
   sk: {
      definiteArticle: '',
      dayMonthFormat: 'D. MMMM',
      celebrationName: 'Názov slávenia',
      rank: 'Stupeň',
      date: 'Dátum',
      liturgicalColors: 'Liturgické farby',
      titles: 'Tituly',
      celebrationCycle: 'Cycklus slávenia',
      lookupSource: 'Zdroj vyhľadávania',
      isPrioritized: 'Je prioritizovaná?',
      grcChangeType: 'Druh zmeny (VRK)'
   }
}

// Table header used by `tablemark`
// Note: Table header should be in format that is accepted by `tablemark`
// Note: `tablemark` accepts the following format too: `{ name: 'column name', align: 'center' },`
const tableHeader = [
   localeConfig[locale].celebrationName,
   localeConfig[locale].rank,
   localeConfig[locale].date,
   localeConfig[locale].liturgicalColors,
   localeConfig[locale].titles,
   localeConfig[locale].celebrationCycle,
   localeConfig[locale].lookupSource,
   localeConfig[locale].isPrioritized
   // localeConfig[locale].grcChangeType
]

// Define the 'preface' to the propers
// TODO: Localise this 'preface'
const tablePreface = '## List of calendar propers\n\nThis list of calendar propers is automatically generated with each commit that lands into romcal codebase. Its primary purpose is to make it easier for non-technical persons (like liturgists) to proof the propers of any calendar without any code knowledge (e.g. where are the celebrations defined in the romcal codebase or how to read and proof the date definition if it is actually correct).\n\nIf you find any (even potential) error in the propers, please raise an [issue](https://github.com/romcal/romcal/issues/new).\n\n<!-- TODO: Restyle the following title in order make it sound better -->\n\n### Data that this list is composed of\n\n1. Calendar propers are listed in alphabetical order with one exception: the General Roman Calendar is put to before other (particular) propers.\n\n2. _Calendar configuration_ currently contains the following configurations:\n\n   - if the _Epiphany of the Lord_ is celebrated on Sunday;\n   - if the _Ascension of the Lord_ is celebrated on Sunday;\n   - if the _Most Holy Body and Blood of Christ_ is celebrated on Sunday.\n\n3. Note that some particular calendars does not have calendar configuration set. In that case, we use the configuration from the General Roman Calendar. The _source_ of calendar configuration is noted before the calendar configuration.\n\n4. Calendar proper itself is typeset in a table with the following columns:\n\n   - `Celebration name`;\n   - `Rank`;\n   - `Date`:\n      - either a fixed date (e.g. `1 January`) or date dependent on another celebration (e.g. `Thursday after Pentecost Sunday`) or a more verbose definition (when a celebration is moved to what date);\n   - `Liturgical color(s)`:\n      - it usually contains only one color, but on _All Souls_, the _Third Sunday of Advent_ and the _Fourth Sunday of Lent_ contains two colours separated by a comma and a space (i.e. `, `);\n   - `Title(s)`:\n      - for celebrations of saints and blesseds, here we list their titles;\n   - `Celebration cycle`:\n      - it can be either _Temporale_ or _Sanctorale_;\n   - `Lookup source`:\n      - `TODO`;\n      - it can be _celebrations_;\n   - `Is prioritized?`:\n      - if it is set to _true_, it will take priority over celebrations that ocur on the same date.\n<!-- TODO: Add another column: `GRC change type` -->\n\n### Calendar propers\n\n'

// Create a list of calendars with `general.ts` being the first (all other calendars listed in alphabetical order)
let calendarsList = fs.readdirSync(calPath)
calendarsList = calendarsList.filter(item => !(/(^(general\.ts|index\.ts|test\.ts)$)/g).test(item));
calendarsList.unshift('general.ts')

// Get locale data
// TODO: Use fallback languages for missing strings.
let enL10nData = getL10nDataObj(l10nPath + '/' + locale + '.ts')

// Write `tablePreface` to `outFile`
fs.writeFileSync(
   outFile,
   tablePreface, {
      encoding: 'utf8',
      flag: 'w'
   }
)

for (let calendar of calendarsList) {
   // Get calendar data
   let calDataObj = getCalDataObj(calPath + '/' + calendar)

   // Create Markdown table for the calendar
   let markdownTable = createMarkdownTable(calDataObj)

   // Write calendar proper to `outFile`
   // TODO: Localise calendar names within romcal codebase
   let calProper = '<details>\n' + '  <summary><b>' + calendar + '</b></summary>\n\n'
   calProper += 'Calendar configuration source: **' + calDataObj.calConfig.configSource + '**.\n\n'
   calProper += localeConfig[locale].definiteArticle + ' _' + enL10nData.celebrations.epiphany + '_ is celebrated on Sunday: **' + calDataObj.calConfig.epiphanyOnSunday + '**.\n\n'
   calProper += localeConfig[locale].definiteArticle + ' _' + enL10nData.celebrations.ascension + '_ is celebrated on Sunday: **' + calDataObj.calConfig.ascensionOnSunday + '**.\n\n'
   calProper += localeConfig[locale].definiteArticle + ' _' + enL10nData.celebrations.corpus_christi + '_ is celebrated on Sunday: **' + calDataObj.calConfig.corpusChristiOnSunday + '**.\n\n'
   calProper += markdownTable
   calProper += '</details>\n'

   // This prevents adding two final newlines
   if (calendarsList[calendarsList.length - 1] != calendar) {
      calProper += '\n'
   }

   // Write calendar proper to `outFile`
   fs.writeFileSync(
      outFile,
      calProper, {
         encoding: 'utf8',
         flag: 'a'
      }
   )
}

/**
 * Gets the calendar data in JSON object
 *
 * @param      {string}  cal     Calendar file with path
 *
 * @returns    {object}  Calendar data
 */
function getCalDataObj(cal) {
   let calData = fs.readFileSync(cal, 'utf8')
   let ascensionOnSunday, corpusChristiOnSunday, epiphanyOnSunday

   // Get calendar configuration
   let configTest = calData.match(/const defaultConfig: RomcalConfigInCalendarDef \| undefined = undefined;/)

   if (configTest != null && configTest[0] == 'const defaultConfig: RomcalConfigInCalendarDef | undefined = undefined;') {
      // TODO: Get the configuration from `general.ts` data, not directly from file
      let calGeneral = cal.replace(/[^/]*\.ts$/, 'general.ts')
      let calDataGeneral = fs.readFileSync(calGeneral, 'utf8')

      // TODO: Instead of `general.ts` use localised name of the calendar (e.g. `Proper of General Roman Calendar`)
      configSource = 'general.ts'
      ascensionOnSunday = calDataGeneral.match(/(?<=ascensionOnSunday: )[^,]*/)[0]
      corpusChristiOnSunday = calDataGeneral.match(/(?<=corpusChristiOnSunday: )[^,]*/)[0]
      epiphanyOnSunday = calDataGeneral.match(/(?<=epiphanyOnSunday: )[^,]*/)[0]
   } else {
      // TODO: Instead of (e.g.) `philippines.ts` use localised name of the calendar (e.g. `Proper of the Philippines`)
      configSource = cal.match(/[^/]*\.ts/)[0]
      ascensionOnSunday = calData.match(/(?<=ascensionOnSunday: )[^,]*/)[0]
      corpusChristiOnSunday = calData.match(/(?<=corpusChristiOnSunday: )[^,]*/)[0]
      epiphanyOnSunday = calData.match(/(?<=epiphanyOnSunday: )[^,]*/)[0]
   }

   // Convert the calendar file to JSON string
   // TODO: Is there a better way to create a JSON from calendar files?
   let removeLinesBefore = calData.replace(/[\s\S]*const _dates: Array<RomcalLiturgicalDayInput> = /m, '')
   let removeLinesAfter = removeLinesBefore.replace(/];[\s\S]*/m, ']')
   let quoteConstants = removeLinesAfter.replace(/(Ranks.[A-Z_]*|LiturgicalColors.[A-Z_]*|Titles.[A-Z_]*|CelebrationsCycle.[A-Z_]*)/g, "'$1'")
   let doubleQuoteDateValues = quoteConstants.replace(/(date: )((\(\(|dayjs|await)[\s\S]*?(\)(?=,$)|\(year\)|\)\(\))(?![; ]))/gm, '$1"$2"')
   let removeComments = doubleQuoteDateValues.replace(/\/\/.*/g, '')
   let removeNewlines = removeComments.replace(/\n/g, ' ')
   let splitByDoubleQuotes = removeNewlines.split('"')

   // Replace single quotes within date value with double quotes
   for (let i=0; i < splitByDoubleQuotes.length; i++) {
      if (i%2 == 1) {
         splitByDoubleQuotes[i] = splitByDoubleQuotes[i].replace(/'/g, '"')
      }
   }

   let joinWithSingleQuotes = splitByDoubleQuotes.join("'")

   // Create and return JSON object with calendar data
   let json = eval('(' + joinWithSingleQuotes + ')')

   // Push calendar configuration into JSON object
   json.calConfig = {}
   json.calConfig.configSource = configSource
   json.calConfig.ascensionOnSunday = ascensionOnSunday
   json.calConfig.corpusChristiOnSunday = corpusChristiOnSunday
   json.calConfig.epiphanyOnSunday = epiphanyOnSunday

   return json
}

/**
 * Gets the locale data in JSON object
 *
 * @param      {string}  locale     locale file with path
 *
 * @returns    {object}  Locale data
 */
function getL10nDataObj(locale) {
   let l10nData = fs.readFileSync(locale, 'utf8')

   // Convert the locale file to JSON string
   let removeLinesBefore = l10nData.replace(/[\s\S]*export default /m, '')
   let removeLinesAfter = removeLinesBefore.replace(/ as RomcalLocale;[\s\S]*/m, '')

   // Create and return JSON object with locale data
   return eval('(' + removeLinesAfter + ')')
}

/**
 * Create markdown table
 *
 * @param      {object}  json    JSON object containing celebration definitions
 *
 * @returns    {string}  Markdown table with calendar proper
 */
function createMarkdownTable(json) {
   let mdTableObj = new Array()

   for (let i=0; i < json.length; i++) {
      let celebration = json[i]
      mdTableObj[i] = {}

      // TODO: add additional column: GRC change type

      for (let key in celebration) {
         switch(key) {
            case 'key':
                  if (celebration.source == 'celebrations') {
                     mdTableObj[i].celebrationName = enL10nData.celebrations[celebration.key]
                  } else {
                     mdTableObj[i].celebrationName = enL10nData.sanctoral[celebration.key]
                  }
               break
            case 'rank':
                  let rank = celebration.rank.replace(/Ranks\./, '')
                  mdTableObj[i].rank = enL10nData.ranks[rank]
               break
            case 'liturgicalColors':
                  let litColsOutput = ''

                  if (Array.isArray(celebration.liturgicalColors)) {
                     for (let i=0; i < celebration.liturgicalColors.length; i++) {
                        if (i != 0) {
                           litColsOutput += ', '
                        }

                        let liturgicalColors = celebration.liturgicalColors[i].replace(/LiturgicalColors\./, '')
                        litColsOutput += enL10nData.liturgicalColors[liturgicalColors]
                     }
                  } else {
                     let liturgicalColors = celebration.liturgicalColors.replace(/LiturgicalColors\./, '')
                     litColsOutput += enL10nData.liturgicalColors[liturgicalColors]
                  }

                  mdTableObj[i].liturgicalColors = litColsOutput
               break
            case 'cycles':
                  // TODO: Ask @emagnier if there the default celebration cycle is temporale; if yes, we could output it by default (i.e. when `cycles` object is empty)
                  let celebrationCycle = celebration.cycles.celebrationCycle.replace(/CelebrationsCycle\./, '')
                  // TODO: Use the following line when cycles are localised
                  // mdTableObj[i].celebrationCycle = enL10nData.celebrationCycle[celebrationCycle]

                  mdTableObj[i].celebrationCycle = celebrationCycle
               break
            case 'metadata':
               // TODO: Ask @emagnier if there are currently any othe metadata types besides `titles`

               let titlesOutput = ''

               for (let i=0; i < celebration.metadata.titles.length; i++) {
                  if (i != 0) {
                     titlesOutput += ', '
                  }

                  let title = celebration.metadata.titles[i].replace(/Titles\./, '')
                  // TODO: Use the following line when titles are localised
                  // titlesOutput = enL10nData.titles[title]
                  titlesOutput += title
               }

               mdTableObj[i].titles = titlesOutput
               break
            case 'date':
                  switch (true) {
                     case /^dayjs\.utc\(`\${year}-[0-9]+-[0-9]+`\)$/.test(celebration.date):
                     mdTableObj[i].date = eval('(' + celebration[key] + ')').format(localeConfig[locale].dayMonthFormat)
                        break;
                     case /^await.*/.test(celebration.date):
                        mdTableObj[i].date = celebration[key].replace(/[\s\S]*=> {*\s*([\s\S]*}*)\)(\(year\)|\(\))[\s\S]*/, '$1').replace(/  +/g, ' ')
                        break;
                     case /^\(\(\).*=> {/.test(celebration.date):
                        mdTableObj[i].date = celebration[key].replace(/[\s\S]*Dayjs => {\s*([\s\S]*)}\)[\s\S]*/, '$1').replace(/  +/g, ' ')
                        break;
                     case /^\(\(y: number\)[\s\S]*else.*/.test(celebration.date):
                        mdTableObj[i].date = celebration[key].replace(/[\s\S]*=> {*\s*([\s\S]*else[\s\S]*?return [\s\S]*})[\s\S]*}\)(\(year\)|\(\))[\s\S]*/, '$1').replace(/  +/g, ' ')
                        break;
                     case /^\(\(y: number\).*/.test(celebration.date):
                        mdTableObj[i].date = celebration[key].replace(/[\s\S]*=> {*\s*([\s\S]*}*)}?\)(\(year\)|\(\))$/, '$1').replace(/  +/g, ' ')
                        break;
                     default:
                        mdTableObj[i].date = celebration[key].replace(/  +/g, ' ')
                  }
               break
            case 'source':
                  mdTableObj[i].lookupSource = celebration[key]
               break
            case 'prioritized':
                  mdTableObj[i].isPrioritized = celebration[key]
               break
            default:
               mdTableObj[i][key] = celebration[key]
         }
      }
   }

   // Make sure all columns will be present in the Markdown table
   // Note: If a table does not a particular column in any row, it won’t be output. The following commands make sure that the first row (after the header row) contains all the columns (although some of them might be empty).
   if (mdTableObj[0]['celebrationName'] == null) {
      mdTableObj[0]['celebrationName'] = ''
   }

   if (mdTableObj[0]['rank'] == null) {
      mdTableObj[0]['rank'] = ''
   }

   if (mdTableObj[0]['date'] == null) {
      mdTableObj[0]['date'] = ''
   }

   if (mdTableObj[0]['liturgicalColors'] == null) {
      mdTableObj[0]['liturgicalColors'] = ''
   }

   if (mdTableObj[0]['titles'] == null) {
      mdTableObj[0]['titles'] = ''
   }

   if (mdTableObj[0]['celebrationCycle'] == null) {
      mdTableObj[0]['celebrationCycle'] = ''
   }

   if (mdTableObj[0]['lookupSource'] == null) {
      mdTableObj[0]['lookupSource'] = ''
   }

   if (mdTableObj[0]['isPrioritized'] == null) {
      mdTableObj[0]['isPrioritized'] = ''
   }

   return tablemark(mdTableObj, {columns: tableHeader})
}
```
</details>

**Comment by tukusejssirs** [comment]
With all the changes in the TS branch, now I think that the generation of propers should be ported to TypeScript, because the celebration metadata can be inherited or generated by a script  and therefore they are not within a single which could be processed.

Therefore I think we need a romcal option (just like `year` or `locale`) using which one could generate proper for either one or more or all calendars supported by romcal.
